# Generated by Django 5.0.6 on 2024-07-04 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_rename_end_date_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='backend_app.booking'),
            preserve_default=False,
        ),
    ]
